services:
  mysql:
    image: mysql:latest
    container_name: fantasy_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: fantasy_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: fantasy_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
